language: node_js
node_js:
- "4"
- "stable"
sudo: false
cache:
  directories:
  - node_modules

before_install:
- npm install google-closure-library
- npm install google-closure-compiler
- npm install webdriverio
- npm install typescript
- npm install gulp
- npm install gulp-tsb
- npm install merge-stream
- npm install gulp-bump
- npm install rimraf
- npm install webpack
- npm install copy-webpack-plugin
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library
before_script:
  - export DISPLAY=:99.0
  - tests/scripts/setup_linux_env.sh
  - sleep 2

script:
  - set -x
  - npm test
  - cd tests/compile; compile.sh; cd ..

after_script:
- |
  # RELEASE_BRANCHES and NPM_ACCESS_TOKEN defined in Travis settings panel
  declare exitCode
  $(npm bin)/travis-after-all
  exitCode=$?
  if [[
    # Execute after all jobs finish successfully
    $exitCode = 0 &&
    # Only release on tagged branches
    $TRAVIS_TAG &&
    # Don't release on PR builds
    $TRAVIS_PULL_REQUEST = "false"
  ]]; then
    # Authenticate NPM
    echo "//registry.npmjs.org/:_authToken=\${NPM_ACCESS_TOKEN}" > .npmrc
    # Set version to timestamp
    npm --no-git-tag-version version $($(npm bin)/json -f package.json version)-prerelease.$(date +%s)
    npm publish
    # Publish to gh-pages as most recent committer
    git config --global user.email $(git log --pretty=format:"%ae" -n1)
    git config --global user.name $(git log --pretty=format:"%an" -n1)
    npm run --silent deploy -- -x -r https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  fi
