language: node_js
node_js:
- "4"
- "stable"
sudo: required
addons:
  chrome: stable
cache:
  directories:
  - node_modules

before_install:
- npm install google-closure-library
- npm install google-closure-compiler
- npm install webdriverio
- npm install typescript
- npm install gulp
- npm install gulp-tsb
- npm install merge-stream
- npm install gulp-bump
- npm install rimraf
- npm install webpack
- npm install copy-webpack-plugin
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library
before_script:
  - export DISPLAY=:99.0
  - tests/scripts/setup_linux_env.sh
  - sleep 2

script:
  - set -x
  - npm test
  - cd tests/compile; compile.sh; cd ..

